//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IP_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessory
    {
        public string Name { get; set; }
        public Nullable<int> Car_Chassis { get; set; }
        public string Type { get; set; }
        public int Price { get; set; }
        public bool Availability { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
