//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IP_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Drive
    {
        public string Email { get; set; }
        public int Car_Chassis { get; set; }
        public int Location_ID { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Location Location { get; set; }
        public virtual User User { get; set; }
    }
}
